services:
  - type: web
    name: the-ultimate-downloader
    env: node
    plan: free
    buildCommand: npm install && node -e "require('ytdlp-nodejs').helpers.downloadYtDlp()"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
